service: clash-royale-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2  # 서울 리전
  stage: production
  memorySize: 512
  timeout: 30
  environment:
    SUPERCELL_API_KEY: ${env:SUPERCELL_API_KEY}
    PORT: 3000

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi: '*'

package:
  patterns:
    - '!.git/**'
    - '!frontend/**'
    - '!README.md'
    - '!.env'
    - '!node_modules/**/aws-sdk/**'
